[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "defect_detection"
version = "0.1.0"
description = "Defect detection using computer vision"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.0",
    "torch>=2.0.0",
    "opencv-python>=4.11.0",
    "pillow>=11.1.0",
    "flask>=3.1.0",
    "flask-login>=0.6.3",
    "prometheus_client>=0.21.0",
    "google-cloud-storage>=3.0.0",
    "pyyaml>=6.0.0",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["defect_detection"]

[tool.black]
line-length = 79
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | src/defect-detection
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
known_first_party = ["src"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
default_section = "THIRDPARTY"
line_length = 79
skip = ["src/defect-detection"]

[tool.bandit]
exclude_dirs = ["tests", "venv"]
skips = ["B101"]  # Skip assert warnings

[tool.bandit.any_other_function_with_shell_equals_true]
no_shell = false

# Ignore B104 in specific cases where binding to all interfaces is required and documented
[[tool.bandit.assert_used.skips]]
id = "B104"
reason = "Binding to all interfaces is required and safe in Cloud Run environment"
file = "app.py"
