# Base configuration for defect detection project

# Data paths
data:
  raw_dir: data/raw
  processed_dir: data/processed
  labeled_dir: data/labeled
  model_dir: models
  upload_dir: uploads
  logs_dir: logs

# Image processing
image:
  size: [224, 224]
  channels: 3
  batch_size: 32
  splits:
    train: 0.8
    validation: 0.1
    test: 0.1

# Model configuration
model:
  backbone: resnet50
  weights: imagenet
  num_classes: 2
  learning_rate: 1.0e-5
  epochs: 20
  early_stopping:
    patience: 3
    monitor: val_loss
    mode: min
  reduce_lr:
    patience: 2
    factor: 0.1
    min_lr: 1.0e-7

# Data augmentation
augmentation:
  rotation_range: 20
  width_shift_range: 0.2
  height_shift_range: 0.2
  horizontal_flip: true
  vertical_flip: true
  fill_mode: nearest
  brightness_range: [0.8, 1.2]
  zoom_range: 0.2

# Training
training:
  validation_freq: 1
  save_best_only: true
  save_weights_only: false
  verbose: 1

# Inference
inference:
  confidence_threshold: 0.5
  max_detections: 100
  nms_threshold: 0.45

# Monitoring
monitoring:
  enabled: true
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
  log_dir: logs/metrics
