# Defect Detection CI/CD Pipeline
#
# Required GitHub Secrets:
# - GCP_PROJECT: Google Cloud Project ID
# - GCP_SA_KEY: Google Cloud Service Account key (JSON)
# - SECRET_KEY: Flask application secret key
# - MODEL_BUCKET: GCS bucket name for model storage

name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  PYTHON_VERSION: '3.12'
  DOCKER_IMAGE: defect-detection
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  GCP_REGION: us-central1
  SERVICE_NAME: defect-detection-service
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  MODEL_BUCKET: ${{ secrets.MODEL_BUCKET }}

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install black isort flake8 bandit safety pytest pytest-cov
          pip install -r requirements.txt
          pip install -e .
          
      - name: Check code formatting
        run: |
          black . --check --exclude="\.git/"
          isort . --check --skip .git
          
      - name: Check code quality
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --statistics

      - name: Security check with bandit
        run: bandit -r . -c pyproject.toml

      - name: Check dependencies for known vulnerabilities
        run: safety check

      - name: Run tests with coverage
        run: |
          PYTHONPATH=$PYTHONPATH:$(pwd) pytest tests/ --cov=. --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml

  build:
    name: Build and Push Docker Image
    needs: quality
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.GCP_PROJECT }}
          
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker
        
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            gcr.io/${{ env.GCP_PROJECT }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }}
            gcr.io/${{ env.GCP_PROJECT }}/${{ env.DOCKER_IMAGE }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    name: Deploy to Cloud Run
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Login to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ env.GCP_PROJECT }}
          
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}
          image: gcr.io/${{ env.GCP_PROJECT }}/${{ env.DOCKER_IMAGE }}:${{ github.sha }}
          region: ${{ env.GCP_REGION }}
          env_vars: |
            MODEL_BUCKET=${{ env.MODEL_BUCKET }}
            SECRET_KEY=${{ env.SECRET_KEY }}
