name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov black isort "safety>=3.0.0"
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Security check dependencies
      run: |
        safety check
        
    - name: Lint with flake8
      run: |
        flake8 src/ tests/
        
    - name: Check formatting with black
      run: |
        black --check src/ tests/
        
    - name: Check import sorting with isort
      run: |
        isort --check-only src/ tests/
        
    - name: Test with pytest
      run: |
        pytest tests/ -v --cov=src --cov-report=xml
