name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit "safety>=3.0.0"
          pip install -r requirements.txt

      - name: Run Bandit security scan
        run: |
          bandit -r src/ -ll -ii -x tests/
          
      - name: Run Safety check
        run: |
          safety check

      - name: Run SAST scan
        uses: github/codeql-action/analyze@v2
        with:
          languages: python
          queries: security-and-quality

  build-deploy:
    needs: security-scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests/ --cov=src --cov-report=xml

      - name: Build package
        run: |
          python setup.py sdist bdist_wheel

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          fail_ci_if_error: true

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: defect-detection
          region: us-central1
          source: ./
          env_vars: |
            GOOGLE_CLOUD_PROJECT=${{ secrets.GCP_PROJECT_ID }}
            MODEL_BUCKET=${{ secrets.MODEL_BUCKET }}
            SECRET_KEY=${{ secrets.SECRET_KEY }}
